# Generated by Django 5.1.3 on 2024-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_task_options_alter_tag_name_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="todo.tag"),
        ),
    ]
